# Generated by Django 5.0.7 on 2024-08-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='likes',
        ),
        migrations.AddField(
            model_name='message',
            name='morninglikes',
            field=models.ManyToManyField(blank=True, related_name='morning_liked_messages', to='users.profile'),
        ),
        migrations.AddField(
            model_name='message',
            name='nightlikes',
            field=models.ManyToManyField(blank=True, related_name='night_liked_messages', to='users.profile'),
        ),
    ]
