# Generated by Django 5.0.7 on 2024-07-18 00:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0002_rename_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_mes', models.CharField(max_length=200)),
                ('night_mes', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('nick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
