# Generated by Django 5.0.7 on 2024-08-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_message_likes_message_morninglikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opentime',
            name='morning_time',
            field=models.TimeField(default='05:00:00'),
        ),
        migrations.AlterField(
            model_name='opentime',
            name='night_time',
            field=models.TimeField(default='21:00:00'),
        ),
    ]
