# Generated by Django 5.0.7 on 2024-07-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_opentime_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opentime',
            name='morning_time',
            field=models.TimeField(default='06:00:00'),
        ),
        migrations.AlterField(
            model_name='opentime',
            name='night_time',
            field=models.TimeField(default='23:00:00'),
        ),
    ]
