# Generated by Django 5.0.7 on 2024-07-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='max_members',
            field=models.IntegerField(default=25),
        ),
    ]
