# Generated by Django 5.0.7 on 2024-08-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='introduce',
            field=models.CharField(max_length=100),
        ),
    ]
